/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2020-05-13 10:08:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Connection;
import com.database.ConnectionManager;
import com.helper.UserModel;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.helper.UserModel");
    _jspx_imports_classes.add("com.database.ConnectionManager");
    _jspx_imports_classes.add("com.mysql.jdbc.Connection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://www.jacklmoore.com/colorbox/example1/colorbox.css\" />\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\t<div class=\"scrollbar-inner sidebar-wrapper\">\r\n");
      out.write("\t\t");

			UserModel um = (UserModel) session.getAttribute("USER_MODEL");
			String user = um.getUid();
			System.out.println(um.getRole());
			if (um != null) {

				if (um.getRole().equalsIgnoreCase("1")) {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"user\">\r\n");
      out.write("\t\t\t<div class=\"photo\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/assets/img/profile.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t\t<a class=\"\"> <span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"user-level text-capitalize \">");
      out.print(um.getFname());
      out.write(' ');
      out.print(um.getLname());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(um.getEmail());
      out.write("\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\">\r\n");
      out.write("\t\t\t <a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/dashboard.jsp  \"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"la la-home\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Home</p>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/checkResume.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                  la la-cloud-upload\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Upload Resume</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/jobRecruite.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                  la la-laptop\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Post Job</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/searchCandidates.jsp\">\r\n");
      out.write("\t\t\t\t\t<i class=\"\r\n");
      out.write("              la la-search search-icon\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Find Candidates</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/viewJobApplied.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                  la la-laptop\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Posted Jobs</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                  la la-sign-out\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Sign Out</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<ul class=\"nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"user\">\r\n");
      out.write("\t\t\t\t<div class=\"photo\">\r\n");
      out.write("\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/assets/img/profile.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t\t\t<a class=\"\"> <span> <span class=\"user-level\">");
      out.print(um.getFname());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(um.getEmail());
      out.write("\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/dashboard.jsp  \"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"la la-home\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Home</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/uploadResume.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                  la la-cloud-upload\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Upload</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t");
if(ConnectionManager.getCount(um.getUid())){
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/jobs.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                  la la-binoculars\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Find Jobs</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/viewResume.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                 la la-file-pdf-o\"></i>\r\n");
      out.write("\t\t\t\t\t<p>My Resume</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/candidateApliedJob.jsp\">\r\n");
      out.write("\t\t\t\t\t<i class=\"\r\n");
      out.write("               la la-filter\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Applied Jobs</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/jobRecommendation.jsp\">\r\n");
      out.write("\t\t\t\t\t<i class=\"\r\n");
      out.write("               la la-filter\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Skills Recommendation</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item update-pro\"><a type=\"button\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"\r\n");
      out.write("                  la la-sign-out\"></i>\r\n");
      out.write("\t\t\t\t\t<p>Sign Out</p>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			}
			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://www.jacklmoore.com/colorbox/jquery.colorbox.js\"></script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
